### ISSUE TITLE
Beta 6 causes tsc to fail when using  typeroots and types in tsconfig.json

### ISSUE THREAD

**Issue by jcwchriswalker** [TypeStrong/grunt-ts#391]
This may be more of a todo since the current grunt-ts does not have built-in support ts 2.1 yet and the type properties that seem to cause the error are tsc 2.1 additions but it worked in grunt-ts 5.5.1-
**tsconfig.json**
```{
    "compilerOptions": {
        "noImplicitAny": true,
        "noEmitOnError": true,
        "removeComments": false,
        "strictNullChecks": false,
        "sourceMap": false,
        "jsx": "react",
        "target": "es5",
        "moduleResolution": "node",
        "outFile": "../tiles/dashboardtiles.js",
        "typeRoots": ["../../../../node_modules/@types"],
        "types": ["jquery","jqueryui","typeahead"]
    },
    "files": [
        "../../../../bower_components/moment/moment.d.ts",
        "../../../typings/igniteui.d.ts",
        "../../../typings/dashboard.d.ts",
        "../BaseModel.ts",
        "../Tiles/BaseController.ts",
        "../Tiles/BaseSettings.ts",
        "../Tiles/ResponseTimes/ResponseTimes.ts",
        "../Tiles/Messages/Messages.ts",
        "../Tiles/UserCounts/UserCounts.ts",
        "../Tiles/TransactionCounts/TransactionCounts.ts",
        "../Tiles/Availability/Availability.ts",
        "../Tiles/Metrics/Metrics.ts"
    ]
  
}
```
**gruntfile.js section**
```
ts: {
           dashboard_tiles: {
                options: {
                    experimentalDecorators: true,
                    emitDecoratorMetadata: true,
                    noImplicitAny: true,
                },
                baseDir: 'scripts/typescript/',
                tsconfig: 'scripts/typescript/dashboard/performancemanagement/tsconfig.json'
            }
        },
```
**Error message produced with Beta 6**
```
error TS6053: File ',"jqueryui","typeahead".ts' not found. [C:\Development\myprog.csproj]
  scripts/typescript/dashboard/Tiles/Metrics/Metrics.ts(777,54): error TS2339: Property 'typeahead' does not exist on type 'JQuery'. 
```

Using the 5.5.1 grunt plugin does not produce this error.

**Comment by nycdotnet** [comment]
Can you please update to the very latest (6.0.0-beta.9 from just a few minutes ago) and please also add 
`listFiles: true` to your options?

Thank you for the report!

**Comment by jcwchriswalker** [comment]
Thanks for the quick reply. I updated grunt-ts to beta 9.  I hope this is what you want.

**gruntfile section**
```
dashboard_tiles: {
                options: {
                    experimentalDecorators: true,
                    emitDecoratorMetadata: true,
                    noImplicitAny: true,
                    listFiles: true
                },
                baseDir: 'scripts/typescript/',
                tsconfig: 'scripts/typescript/dashboard/performancemanagement/tsconfig.json'
            }
```

output from **grunt ts:dashboard_tiles --verbose**
```
Initializing
Command-line options: --verbose

Reading "gruntfile.js" Gruntfile...OK

Registering Gruntfile tasks.
Reading package.json...OK
Parsing package.json...OK
Initializing config...OK

Registering "grunt-contrib-concat" local Npm module tasks.
Reading D:\Development\Reveille\WWWRoot\Reveille\node_modules\grunt-contrib-concat\package.json...OK
Parsing D:\Development\Reveille\WWWRoot\Reveille\node_modules\grunt-contrib-concat\package.json...OK
Loading "concat.js" tasks...OK
+ concat

Registering "grunt-contrib-uglify" local Npm module tasks.
Reading D:\Development\Reveille\WWWRoot\Reveille\node_modules\grunt-contrib-uglify\package.json...OK
Parsing D:\Development\Reveille\WWWRoot\Reveille\node_modules\grunt-contrib-uglify\package.json...OK
Loading "uglify.js" tasks...OK
+ uglify

Registering "grunt-contrib-clean" local Npm module tasks.
Reading D:\Development\Reveille\WWWRoot\Reveille\node_modules\grunt-contrib-clean\package.json...OK
Parsing D:\Development\Reveille\WWWRoot\Reveille\node_modules\grunt-contrib-clean\package.json...OK
Loading "clean.js" tasks...OK
+ clean

Registering "grunt-contrib-cssmin" local Npm module tasks.
Reading D:\Development\Reveille\WWWRoot\Reveille\node_modules\grunt-contrib-cssmin\package.json...OK
Parsing D:\Development\Reveille\WWWRoot\Reveille\node_modules\grunt-contrib-cssmin\package.json...OK
Loading "cssmin.js" tasks...OK
+ cssmin

Registering "grunt-contrib-handlebars" local Npm module tasks.
Reading D:\Development\Reveille\WWWRoot\Reveille\node_modules\grunt-contrib-handlebars\package.json...OK
Parsing D:\Development\Reveille\WWWRoot\Reveille\node_modules\grunt-contrib-handlebars\package.json...OK
Loading "handlebars.js" tasks...OK
+ handlebars

Registering "grunt-contrib-copy" local Npm module tasks.
Reading D:\Development\Reveille\WWWRoot\Reveille\node_modules\grunt-contrib-copy\package.json...OK
Parsing D:\Development\Reveille\WWWRoot\Reveille\node_modules\grunt-contrib-copy\package.json...OK
Loading "copy.js" tasks...OK
+ copy

Registering "grunt-sass" local Npm module tasks.
Reading D:\Development\Reveille\WWWRoot\Reveille\node_modules\grunt-sass\package.json...OK
Parsing D:\Development\Reveille\WWWRoot\Reveille\node_modules\grunt-sass\package.json...OK

node-sass       3.13.1  (Wrapper)       [JavaScript]
libsass         3.3.6   (Sass Compiler) [C/C++]

Loading "sass.js" tasks...OK
+ sass

Registering "grunt-ts" local Npm module tasks.
Reading D:\Development\Reveille\WWWRoot\Reveille\node_modules\grunt-ts\package.json...OK
Parsing D:\Development\Reveille\WWWRoot\Reveille\node_modules\grunt-ts\package.json...OK
Loading "ts.js" tasks...OK
+ ts

Registering "grunt-tslint" local Npm module tasks.
Reading D:\Development\Reveille\WWWRoot\Reveille\node_modules\grunt-tslint\package.json...OK
Parsing D:\Development\Reveille\WWWRoot\Reveille\node_modules\grunt-tslint\package.json...OK
Loading "tslint.js" tasks...OK
+ tslint
Loading "gruntfile.js" tasks...OK
+ dashboard_healthcheck, dashboard_home, dashboard_scorecard, dashboard_tiles, default, scorecardViewer

Running tasks: ts:dashboard_tiles

Running "ts:dashboard_tiles" (ts) task
Verifying property ts.dashboard_tiles exists in config...OK
File: [no files]
Compiling...
Fast compile will not work when --out is specified. Ignoring fast compilation
Using tsc v2.1.4
bower_components\moment\moment.d.ts scripts\typings\igniteui.d.ts scripts\typings\reveilledashboard.d.ts scripts\typescript\dashboard\BaseModel.ts scripts\typescript\dashboard\Tiles\BaseController.ts scripts\typescript\dashboard\Tiles\BaseSettings.ts scripts\typescript\dashboard\Tiles\ResponseTimes\ResponseTimes.ts scripts\typescript\dashboard\Tiles\Messages\Messages.ts scripts\typescript\dashboard\Tiles\UserCounts\UserCounts.ts scripts\typescript\dashboard\Tiles\TransactionCounts\TransactionCounts.ts scripts\typescript\dashboard\Tiles\Availability\Availability.ts scripts\typescript\dashboard\Tiles\Metrics\Metrics.ts --emitDecoratorMetadata --noImplicitAny --noEmitOnError --experimentalDecorators --jsx react --moduleResolution node --listFiles --types "jquery","jqueryui","typeahead" --typeRoots "..\..\..\..\node_modules\@types" --target ES5 --out scripts/typescript/dashboard/tiles/dashboardtiles.js
error TS6053: File ',"jqueryui","typeahead".ts' not found.
scripts/typescript/dashboard/Tiles/Metrics/Metrics.ts(803,54): error TS2339: Property 'typeahead' does not exist on type 'JQuery'.
scripts/typescript/dashboard/Tiles/Metrics/Metrics.ts(826,32): error TS2503: Cannot find namespace 'Twitter'.
scripts/typescript/dashboard/Tiles/Metrics/Metrics.ts(835,33): error TS2503: Cannot find namespace 'Twitter'.
scripts/typescript/dashboard/Tiles/Metrics/Metrics.ts(838,58): error TS2339: Property 'typeahead' does not exist on type 'JQuery'.
D:/Development/Reveille/WWWRoot/Reveille/node_modules/typescript/lib/lib.d.ts
bower_components/moment/moment.d.ts
scripts/typings/igniteui.d.ts
scripts/typings/reveilledashboard.d.ts
scripts/typescript/dashboard/BaseModel.ts
scripts/typescript/dashboard/Tiles/BaseController.ts
scripts/typescript/dashboard/Tiles/BaseSettings.ts
scripts/typescript/dashboard/Tiles/ResponseTimes/ResponseTimes.ts
scripts/typescript/dashboard/Tiles/Messages/Messages.ts
scripts/typescript/dashboard/Tiles/UserCounts/UserCounts.ts
scripts/typescript/dashboard/Tiles/TransactionCounts/TransactionCounts.ts
scripts/typescript/dashboard/Tiles/Availability/Availability.ts
scripts/typescript/dashboard/Tiles/Metrics/Metrics.ts
D:/Development/Reveille/WWWRoot/Reveille/node_modules/@types/jquery/index.d.ts

>> 5 non-emit-preventing type warnings
>> Error: tsc return code: 1
Warning: Task "ts:dashboard_tiles" failed. Use --force to continue.

Aborted due to warnings.
```

**Comment by nycdotnet** [comment]
This is exactly what I needed.  It's puzzling, though.  What happens when you run this?

```
node node_modules\typescript\lib\tsc.js bower_components\moment\moment.d.ts scripts\typings\igniteui.d.ts scripts\typings\reveilledashboard.d.ts scripts\typescript\dashboard\BaseModel.ts scripts\typescript\dashboard\Tiles\BaseController.ts scripts\typescript\dashboard\Tiles\BaseSettings.ts scripts\typescript\dashboard\Tiles\ResponseTimes\ResponseTimes.ts scripts\typescript\dashboard\Tiles\Messages\Messages.ts scripts\typescript\dashboard\Tiles\UserCounts\UserCounts.ts scripts\typescript\dashboard\Tiles\TransactionCounts\TransactionCounts.ts scripts\typescript\dashboard\Tiles\Availability\Availability.ts scripts\typescript\dashboard\Tiles\Metrics\Metrics.ts --emitDecoratorMetadata --noImplicitAny --noEmitOnError --experimentalDecorators --jsx react --moduleResolution node --listFiles --types "jquery","jqueryui","typeahead" --typeRoots "..\..\..\..\node_modules\@types" --target ES5 --out scripts/typescript/dashboard/tiles/dashboardtiles.js
```

**Comment by nycdotnet** [comment]
Also please run this: 
```
node node_modules\typescript\lib\tsc.js --version
```

**Comment by jcwchriswalker** [comment]
**node node_modules\typescript\lib\tsc.js --version**
```Version 2.1.4```

**node node_modules\typescript\lib\tsc.js bower_components\moment\moment.d.ts scripts\typings\igniteui.d.ts scripts\typings\reveilledashboard.d.ts scripts\typescript\dashboard\BaseModel.ts scripts\typescript\dashboard\Tiles\BaseController.ts scripts\typescript\dashboard\Tiles\BaseSettings.ts scripts\typescript\dashboard\Tiles\ResponseTimes\ResponseTimes.ts scripts\typescript\dashboard\Tiles\Messages\Messages.ts scripts\typescript\dashboard\Tiles\UserCounts\UserCounts.ts scripts\typescript\dashboard\Tiles\TransactionCounts\TransactionCounts.ts scripts\typescript\dashboard\Tiles\Availability\Availability.ts scripts\typescript\dashboard\Tiles\Metrics\Metrics.ts --emitDecoratorMetadata --noImplicitAny --noEmitOnError --experimentalDecorators --jsx react --moduleResolution node --listFiles --types "jquery","jqueryui","typeahead" --typeRoots "..\..\..\..\node_modules\@types" --target ES5 --out scripts/typescript/dashboard/tiles/dashboardtiles.js**

```
D:/Development/Reveille/WWWRoot/Reveille/node_modules/typescript/lib/lib.d.ts
bower_components/moment/moment.d.ts
scripts/typings/igniteui.d.ts
scripts/typings/reveilledashboard.d.ts
scripts/typescript/dashboard/BaseModel.ts
scripts/typescript/dashboard/Tiles/BaseController.ts
scripts/typescript/dashboard/Tiles/BaseSettings.ts
scripts/typescript/dashboard/Tiles/ResponseTimes/ResponseTimes.ts
scripts/typescript/dashboard/Tiles/Messages/Messages.ts
scripts/typescript/dashboard/Tiles/UserCounts/UserCounts.ts
scripts/typescript/dashboard/Tiles/TransactionCounts/TransactionCounts.ts
scripts/typescript/dashboard/Tiles/Availability/Availability.ts
scripts/typescript/dashboard/Tiles/Metrics/Metrics.ts
D:/Development/Reveille/WWWRoot/Reveille/node_modules/@types/jquery/index.d.ts
D:/Development/Reveille/WWWRoot/Reveille/node_modules/@types/jqueryui/index.d.ts
D:/Development/Reveille/WWWRoot/Reveille/node_modules/@types/typeahead/index.d.ts
```

**Comment by nycdotnet** [comment]
Odd - it worked.

What happens if you add a custom `compiler` directive to your gruntfile?.

```
dashboard_tiles: {
                options: {
                    experimentalDecorators: true,
                    emitDecoratorMetadata: true,
                    noImplicitAny: true,
                    listFiles: true,
                    compiler: "node_modules/typescript/lib/tsc.js"
                },
                baseDir: 'scripts/typescript/',
                tsconfig: 'scripts/typescript/dashboard/performancemanagement/tsconfig.json'
            }
```

Otherwise, we

**Comment by nycdotnet** [comment]
I am continuing to look at this and I'm scratching my head.  The error is something to do with how `types` got passed to the command-line.  In your original report, this error is present:

```
error TS6053: File ',"jqueryui","typeahead".ts' not found.
```

Which makes me think that TypeScript saw the original item inside `types` correctly, but not the rest of them.  However, I'm able to run some tests with TypeScript 2.1.4 on my computer (also Windows) and something like this works fine:

```
node node_modules\typescript\lib\tsc.js test.ts --types "jquery","jqueryui" --noImplicitAny --typeRoots "..\testgruntts391-up-a-level\types1\@types","..\testgruntts391-up-a-level\types2"
```


Your original command line (once you added --verbose) was this:
```
bower_components\moment\moment.d.ts scripts\typings\igniteui.d.ts scripts\typings\reveilledashboard.d.ts scripts\typescript\dashboard\BaseModel.ts scripts\typescript\dashboard\Tiles\BaseController.ts scripts\typescript\dashboard\Tiles\BaseSettings.ts scripts\typescript\dashboard\Tiles\ResponseTimes\ResponseTimes.ts scripts\typescript\dashboard\Tiles\Messages\Messages.ts scripts\typescript\dashboard\Tiles\UserCounts\UserCounts.ts scripts\typescript\dashboard\Tiles\TransactionCounts\TransactionCounts.ts scripts\typescript\dashboard\Tiles\Availability\Availability.ts scripts\typescript\dashboard\Tiles\Metrics\Metrics.ts --emitDecoratorMetadata --noImplicitAny --noEmitOnError --experimentalDecorators --jsx react --moduleResolution node --listFiles --types "jquery","jqueryui","typeahead" --typeRoots "..\..\..\..\node_modules\@types" --target ES5 --out scripts/typescript/dashboard/tiles/dashboardtiles.js
```

Which to me looks the same in terms of how --types and --typeRoots is specified versus mine, yet in your original report, tsc is getting it wrong somehow and thinking `,"jqueryui","typeahead".ts` is a file.

**Comment by jcwchriswalker** [comment]
I'm glad you are scratching your head as well because I kept saying- 'what is wrong with my types:[] setting?'  Yet the only thing we are changing is the grunt-ts version.

**Comment by nycdotnet** [comment]
Is your project open source or is there any way I could take a look at it myself?

**Comment by jcwchriswalker** [comment]
Unfortunately its part of a commercial product.  Did we ever determine the version of Node.js that you and I are using?

**Comment by nycdotnet** [comment]
We do CI tests on Node 0.10, 4, 5, and 6, and I develop on Node 7, so I suspect it's not that.  I am still thinking it's something wonky about TypeScript.  If you delete your node_modules/typescript folder and `npm install` again, does it change anything?

**Comment by jcwchriswalker** [comment]
I will wait on the new beta. Thanks. For the mean time I set our build machines (which flagged the problem) to just use grunt-ts@5.5.2

**Comment by nycdotnet** [comment]
Would you please try again with `grunt-ts@6.0.0-beta.10` which has just been published to npm.  Upon messing with it more, I think that tsc wants the quoting like this: 
```
node node_modules\typescript\lib\tsc.js test.ts --types "jquery,jqueryui"
```
Instead of like this which is what earlier betas were doing:
```
node node_modules\typescript\lib\tsc.js test.ts --types "jquery","jqueryui"
```

**Comment by jcwchriswalker** [comment]
Hey Steve,
I am looking at the tsconfig.json  documentation:
https://www.typescriptlang.org/docs/handbook/tsconfig-json.html

It shows that the compilerOptions for types needs to be 
"types":["a", "b", "c"]

I will try beta-10 but I will keep the types: as documented..

**Comment by nycdotnet** [comment]
Hi - yes you're correct on both the tsconfig.json and also in grunt-ts.  What I meant was "when passing --types to tsc.js on the command-line, it expects the text as one string with internal commas for separators".  There is no change to what you need to do, but this new version should (hopefully) pass the arguments in the manner tsc expects.

**Comment by jcwchriswalker** [comment]
Steve- . Looks like Beta-10 is a winner! I confirmed by trying it on Beta-9 (failed) then Beta-10 (passed). Thanks!

**Comment by nycdotnet** [comment]
Excellent.  Thank you for all the testing.
