### ISSUE TITLE
grunt-ts 5.3.x fails whereas grunt-ts 5.1.x succesfully builds the project

### ISSUE THREAD

**Issue by vp2177** [TypeStrong/grunt-ts#326]
The code has several `TS2307: Cannot find module` warnings.
However it successfully builds with grunt-ts 5.1.x, but after upgrading to grunt-ts 5.3.x, the grunt task fails as tsc returns a code `2`

**Comment by nycdotnet** [comment]
Hi,

It's hard to help based on this error report.  What version of TypeScript are you using?  What's in your Gruntfile?  What's in your tsconfig.json file?

Please run Grunt with the `--verbose` switch to get the command-line parameters and provide them here.  Can you run tsc manually to get a different result?

Thanks,

-Steve O

**Comment by vp2177** [comment]
I have created a minimal testcase here: [grunt-ts-326](/vp2177/grunt-ts-326)

- `git clone` it; `cd grunt-ts-326`
- `npm update`
- `npm run grunt` - works *fine*
- `npm i grunt-ts@5.3.x`
- `npm run grunt` - *fails*

**Comment by nycdotnet** [comment]
Hi there - thank you so much for this repro.  Sorry it took so long to get back to you on this.

Unfortunately this was a regression in grunt-ts v5.0.0 that was fixed in v5.2.0.  See here: https://github.com/TypeStrong/grunt-ts/blob/master/CHANGELOG.md#v520-2015-11-21

The good news is that you just need to put `failOnTypeErrors: false` in your target or task `options` object, and you'll get the behavior that you observed in grunt-ts v5.1.

For example, here would be the fixed Gruntfile.js for your minimal test case:

```javascript
module.exports = function(grunt) {
    grunt.initConfig({
        ts: {
            all: {
                tsconfig: true,
                options: {
                  failOnTypeErrors: false
                }
            }
        }
    })
    grunt.loadNpmTasks("grunt-ts")
    grunt.registerTask("default", "ts")
}
```

Again - I'm so sorry it took so long to get back to you on this.  I really appreciate your test case and hopefully this will resolve your issue.  Thank you for contributing!

**Comment by vp2177** [comment]
Thank you, yes this resolves the issue.
